version: '3.4'

services:
  catalogdb:
    image: mongo

  api.catalog:
    image: ${DOCKER_REGISTRY-}apicatalog
    build:
      context: .
      dockerfile: Services/Catalog/API.Catalog/Dockerfile

volumes:
  mongo_data:
